[package]
name = "smart_account_custom_ed25519"
edition = "2024"

[dependencies]
Iota = { local = "../../../../crates/iota-framework/packages/iota-framework" }

[addresses]
smart_account_custom_ed25519 = "0x0"

[dev-dependencies]

[dev-addresses]
